branch-defaults:
  develop:
    environment: staging
  master:
    environment: sample-app-staging
global:
  application_name: django-docker-sample
  default_ec2_keyname: mwas
  default_platform: Multi-container Docker 1.6.2 (Generic)
  default_region: eu-west-1
  profile: null
  sc: git
